import json
from pathlib import Path

from usage_bridge.render import author_file, merge_all, merge_feature, render_all_md, render_feature_md

GOLD = Path(__file__).parent / "golden" / "feature"
ZERO = {"input": 0, "output": 0, "cache_read": 0, "cache_write_5m": 0, "cache_write_1h": 0}


def sources():
    return [json.loads(p.read_text(encoding="utf-8")) for p in sorted((GOLD / "sources").glob("*.json"))]


def run_obj(phase, kind, start, calls=1, attributed_by="timeline"):
    usage = {**ZERO, "input": 100 * calls}
    return {"phase": phase, "kind": kind, "label": "/x", "run": 1, "start_ts": start, "end_ts": start,
            "attributed_by": attributed_by, "calls": calls, "usage": usage, "cost_usd": 0.01,
            "models": {"claude-test-1": {"calls": calls, "usage": usage, "cost_usd": 0.01}},
            "subagents": {"count": 0, "usage": dict(ZERO), "cost_usd": None}, "skills": []}


def session(session_id, runs):
    return {"session_id": session_id, "first_ts": runs[0]["start_ts"], "last_ts": runs[-1]["end_ts"],
            "after_clear": False, "dominant_model": "claude-test-1", "main_calls": 1, "final_context_tokens": 0,
            "repriming": None, "splitting": None, "compactions": [], "runs": runs}


def source(author, sessions):
    generator = {"usage_bridge": "0.1.0", "token_usage": "main@f407827", "pricing": "bundled", "pricing_sha256": "aa"}
    return author_file("001-a", "specs/001-a", author, "abcdef", generator, sessions, "complete", [], [])


def two_authors_with_plan_runs():
    a = source("anna", [session("s-anna-1", [run_obj("plan", "core", "2026-09-29T10:00:00.000Z")])])
    b = source("bob", [session("s-bob-1", [run_obj("plan", "core", "2026-09-29T11:00:00.000Z")])])
    return a, b


def source_with_phases(phases):
    runs = [run_obj(p, "extension" if "." in p else ("other" if p == "other" else "core"),
                    f"2026-09-29T1{i}:00:00.000Z") for i, p in enumerate(phases)]
    return source("anna", [session("s1", runs)])


def test_md_matches_golden(update_golden):
    out = render_feature_md(sources())
    if update_golden:
        (GOLD / "token-usage.md").write_text(out, encoding="utf-8", newline="\n")
    assert out == (GOLD / "token-usage.md").read_text(encoding="utf-8")


def test_md_is_order_independent():
    a, b = sources()
    assert render_feature_md([a, b]) == render_feature_md([b, a])


def test_md_has_lf_and_generated_comment():
    out = render_feature_md(sources())
    assert out.startswith("<!-- Generated by Usage Bridge — do not edit.") and "\r" not in out


def test_run_numbers_recounted_across_authors():
    a, b = two_authors_with_plan_runs()
    rows = [line for line in render_feature_md([a, b]).splitlines() if line.startswith("| plan |")]
    assert [row.split("|")[2].strip() for row in rows[1:]] == ["1", "2"]   # rows[0] is the summary row


def test_phase_order_extension_rows_and_no_constitution():
    md = render_feature_md([source_with_phases(["implement", "superspec.brainstorm", "specify", "other"])])
    summary = [line.split("|")[1].strip() for line in md.split("## Runs")[0].splitlines()
               if line.startswith("| ") and "Phase" not in line]
    assert summary == ["specify", "implement", "superspec.brainstorm", "other work"] and "constitution" not in md


def test_pricing_groups_and_partial_header():
    a, b = sources()
    b = {**b, "generator": {**b["generator"], "pricing": "bundled+overrides", "pricing_sha256": "ffff"},
         "completeness": "partial", "partial_reasons": ["deadline"]}
    head = render_feature_md([a, b]).splitlines()[3]
    assert "pricing: bundled (anna) · bundled+overrides (jakub)" in head and "partial (deadline)" in head


def test_unpriced_models_footnote():
    a = source_with_phases(["plan"])
    a["unpriced_models"] = ["mystery-model"]
    assert "mystery-model" in render_feature_md([a])


def test_merge_feature_totals():
    rep = merge_feature(sources())
    assert (rep["schema"], rep["schema_version"]) == ("usage-bridge/feature-report", 1)
    assert rep["totals"]["tokens"] == sum(p["tokens"] for p in rep["phases"])
    assert all("author" in r for r in rep["runs"]) and rep["totals"]["sessions"] == 3


def test_all_report():
    rep = merge_all([merge_feature(sources())], project={"tokens": 5}, unattributed={"tokens": 7})
    md = render_all_md(rep)
    assert rep["schema"] == "usage-bridge/repo-report" and "project" in md and "unattributed (this machine only)" in md
    assert [p["phase"] for p in rep["phase_averages"]][:2] == ["specify", "plan"]
