"""Output formats (spec §4): per-author JSON, the merged Markdown view and the report views.

Everything here is a pure function of its inputs except ``write_if_changed``; the same inputs always
render to the same bytes, whoever renders them.
"""

from __future__ import annotations

import json
import logging
import os
import textwrap
import time
from collections import Counter
from collections.abc import Sequence
from pathlib import Path
from typing import Any

from .phases import CORE_PHASES
from .timefmt import parse_ts

SCHEMA_FEATURE = "usage-bridge/feature-usage"
SCHEMA_REPORT = "usage-bridge/feature-report"
SCHEMA_REPO = "usage-bridge/repo-report"
SCHEMA_VERSION = 1
RUNTIME = "claude"
EMPTY = "—"
USAGE_KEYS = ("input", "output", "cache_read", "cache_write_5m", "cache_write_1h")
SDD_ORDER = tuple(p for p in CORE_PHASES if p != "constitution")
GENERATED_COMMENT = ("<!-- Generated by Usage Bridge — do not edit. On a merge conflict keep either side; "
                     "the next capture regenerates this file. -->")
DISCLAIMER = ("> Estimated costs use API list prices from the pinned token-usage pricing table plus team overrides.",
              "> Subscription plans are not billed per token.")
ASSUMPTIONS = ("Assumes the continued session would have kept the previous context cached without compaction; "
               "the new session's re-reading of artifacts is not credited to continuing; "
               "rates of the new session's main model.")
WRAP_WIDTH = 118
BRANCH_NOTE = "† attributed by git branch (no timeline entry)."
PARTIAL_TEXT = {
    "deadline": "the capture deadline was reached before every session was read",
    "subagent-in-progress": "a subagent was still running",
}


# -- formatting ----------------------------------------------------------------------------------

def fmt_tokens(n: int) -> str:
    """Compact token count: 999, 4.1k, 212k, 17.6M."""
    n = int(n or 0)
    if n < 1000:
        return str(n)
    if n < 10_000:
        return f"{n / 1000:.1f}k"
    thousands = round(n / 1000)
    if thousands < 1000:
        return f"{thousands}k"
    return f"{n / 1_000_000:.1f}M"


def fmt_cost(x: float | None) -> str:
    return EMPTY if x is None else f"${x:.2f}"


def fmt_ts(value: str | None) -> str:
    if not value:
        return EMPTY
    try:
        return parse_ts(value).strftime("%m-%d %H:%M")
    except ValueError:
        return EMPTY


def _rounded(value: Any) -> Any:
    if isinstance(value, float):
        return round(value, 6)
    if isinstance(value, dict):
        return {key: _rounded(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [_rounded(item) for item in value]
    return value


def dump_json(obj: Any) -> str:
    """Stable JSON text: key order kept, floats rounded to 6 decimals, UTF-8 characters as-is, LF."""
    return json.dumps(_rounded(obj), indent=2, ensure_ascii=False) + "\n"


# -- per-author source file ----------------------------------------------------------------------

def author_file(feature_id: str, feature_dir: str, author: str, machine: str, generator: dict[str, str],
                sessions: list[dict[str, Any]], completeness: str, partial_reasons: list[str],
                unpriced: list[str]) -> dict[str, Any]:
    ordered = sorted(sessions, key=lambda s: (s.get("first_ts") or "", s.get("session_id") or ""))
    stamps = [s.get("last_ts") for s in ordered if s.get("last_ts")]
    return {
        "schema": SCHEMA_FEATURE,
        "schema_version": SCHEMA_VERSION,
        "feature": {"id": feature_id, "directory": feature_dir},
        "author": {"name": author, "machine": machine},
        "generator": dict(generator),
        "runtime": RUNTIME,
        "completeness": completeness,
        "partial_reasons": list(partial_reasons),
        "data_as_of": max(stamps) if stamps else None,
        "unpriced_models": sorted(unpriced),
        "sessions": ordered,
    }


# -- safe writes ---------------------------------------------------------------------------------

def write_if_changed(path: Path, text: str, log: logging.Logger | None = None) -> bool:
    """Atomically replace ``path`` with ``text`` (LF) unless it already holds the same content.

    The comparison ignores CRLF/LF differences so ``core.autocrlf`` checkouts are not rewritten. A
    failed replace (e.g. a Windows sharing violation) is retried once, then skipped; the original
    file is left untouched and no temp file remains. Returns True only when the file was written.
    """
    path = Path(path)
    wanted = text.replace("\r\n", "\n")
    try:
        if path.read_text(encoding="utf-8").replace("\r\n", "\n") == wanted:
            return False
    except (OSError, UnicodeDecodeError):
        pass
    tmp = path.with_name(f".{path.name}.{os.getpid()}.tmp")
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        with tmp.open("w", encoding="utf-8", newline="\n") as fh:
            fh.write(wanted)
    except OSError as exc:
        _discard(tmp)
        if log:
            log.warning("cannot write %s: %s", path, exc)
        return False
    for attempt in range(2):
        try:
            os.replace(tmp, path)
            return True
        except OSError as exc:
            if attempt == 0:
                time.sleep(0.05)
                continue
            if log:
                log.warning("cannot replace %s: %s", path, exc)
    _discard(tmp)
    return False


def _discard(path: Path) -> None:
    try:
        path.unlink()
    except OSError:
        pass


# -- merged feature view -------------------------------------------------------------------------

def _zero() -> dict[str, int]:
    return dict.fromkeys(USAGE_KEYS, 0)


def _add_usage(total: dict[str, int], usage: dict[str, Any]) -> None:
    for key in USAGE_KEYS:
        total[key] += int(usage.get(key) or 0)


def _tokens(usage: dict[str, int]) -> int:
    return sum(int(usage.get(key) or 0) for key in USAGE_KEYS)


def _sum_costs(costs: Sequence[float | None]) -> float | None:
    known = [c for c in costs if c is not None]
    return sum(known) if known else None


def _phase_key(phase: str, kind: str) -> tuple[int, int, str]:
    if kind == "core" and phase in SDD_ORDER:
        return (0, SDD_ORDER.index(phase), phase)
    if phase == "other":
        return (2, 0, phase)
    return (1, 0, phase)


def _display(phase: str) -> str:
    return "other work" if phase == "other" else phase


def _plural(count: int, noun: str) -> str:
    return f"{count} {noun}" if count == 1 else f"{count} {noun}s"


def _cell_cost(value: float | None) -> str:
    return EMPTY if value is None else f"{value:.2f}"


def merge_feature(sources: Sequence[dict[str, Any]]) -> dict[str, Any]:
    """Merge per-author source files into one feature report (schema usage-bridge/feature-report v1)."""
    ordered = sorted(sources, key=lambda s: (s["author"]["name"], s["author"].get("machine", "")))
    feature = dict(ordered[0]["feature"]) if ordered else {"id": "", "directory": ""}
    sessions: list[dict[str, Any]] = []
    runs: list[dict[str, Any]] = []
    for src in ordered:
        author = src["author"]["name"]
        for sess in src.get("sessions", []):
            sessions.append({**sess, "author": author})
            for run in sess.get("runs", []):
                if run.get("phase") != "constitution":
                    runs.append({**run, "author": author, "session_id": sess["session_id"]})
    runs.sort(key=lambda r: (r.get("start_ts") or "", r["session_id"], r.get("label") or ""))
    counters: dict[str, int] = {}
    for run in runs:
        counters[run["phase"]] = counters.get(run["phase"], 0) + 1
        run["run"] = counters[run["phase"]]

    grouped: dict[str, dict[str, Any]] = {}
    for run in runs:
        row = grouped.setdefault(run["phase"], {"phase": run["phase"], "kind": run.get("kind", "core"),
                                                "sessions": set(), "calls": 0, "usage": _zero(), "costs": []})
        row["sessions"].add((run["author"], run["session_id"]))
        row["calls"] += int(run.get("calls") or 0)
        _add_usage(row["usage"], run.get("usage") or {})
        row["costs"].append(run.get("cost_usd"))
    phases = []
    for row in sorted(grouped.values(), key=lambda r: _phase_key(r["phase"], r["kind"])):
        phases.append({"phase": row["phase"], "kind": row["kind"], "sessions": len(row["sessions"]),
                       "calls": row["calls"], "usage": row["usage"], "tokens": _tokens(row["usage"]),
                       "cost_usd": _sum_costs(row["costs"])})

    total_usage = _zero()
    for run in runs:
        _add_usage(total_usage, run.get("usage") or {})
    session_keys = {(s["author"], s["session_id"]) for s in sessions}

    ordered_sessions = sorted(sessions, key=lambda s: (s.get("first_ts") or "", s["author"], s["session_id"]))
    splitting = []
    for sess in ordered_sessions[1:]:
        if sess.get("repriming") is None:
            continue
        own = sorted((r for r in sess.get("runs", []) if r.get("phase") != "constitution"),
                     key=lambda r: r.get("start_ts") or "")
        splitting.append({"session_id": sess["session_id"], "author": sess["author"],
                          "starts_with": own[0]["phase"] if own else None, "repriming": sess["repriming"],
                          "splitting": sess.get("splitting")})
    compactions = [{**c, "author": s["author"], "session_id": s["session_id"]}
                   for s in ordered_sessions for c in s.get("compactions", [])]
    partial = any(src.get("completeness") == "partial" for src in ordered)
    stamps = [src.get("data_as_of") for src in ordered if src.get("data_as_of")]
    return {
        "schema": SCHEMA_REPORT,
        "schema_version": SCHEMA_VERSION,
        "feature": feature,
        "authors": sorted({src["author"]["name"] for src in ordered}),
        "generators": [{"author": src["author"]["name"], **src.get("generator", {})} for src in ordered],
        "completeness": "partial" if partial else "complete",
        "partial_reasons": sorted({reason for src in ordered for reason in src.get("partial_reasons", [])}),
        "data_as_of": max(stamps) if stamps else None,
        "totals": {"sessions": len(session_keys), "runs": len(runs),
                   "calls": sum(int(r.get("calls") or 0) for r in runs),
                   "usage": total_usage, "tokens": _tokens(total_usage),
                   "cost_usd": _sum_costs([r.get("cost_usd") for r in runs])},
        "phases": phases,
        "runs": runs,
        "splitting": splitting,
        "compactions": compactions,
        "unpriced_models": sorted({m for src in ordered for m in src.get("unpriced_models", [])}),
    }


def _header(rep: dict[str, Any]) -> str:
    as_of = EMPTY
    if rep["data_as_of"]:
        as_of = parse_ts(rep["data_as_of"]).strftime("%Y-%m-%d %H:%M") + " UTC"
    versions = ", ".join(sorted({g.get("token_usage") or EMPTY for g in rep["generators"]}))
    groups: dict[tuple[str, str], set[str]] = {}
    for g in rep["generators"]:
        groups.setdefault((g.get("pricing") or EMPTY, g.get("pricing_sha256") or ""), set()).add(g["author"])
    pricing = " · ".join(f"{label} ({', '.join(sorted(authors))})"
                         for (label, _), authors in sorted(groups.items(), key=lambda kv: (kv[0][0], sorted(kv[1]))))
    state = rep["completeness"]
    if state == "partial" and rep["partial_reasons"]:
        state += f" ({', '.join(rep['partial_reasons'])})"
    return (f"data as of {as_of} · token-usage {versions} · pricing: {pricing} · runtime: {RUNTIME} · {state} · "
            f"authors: {', '.join(rep['authors'])}")


def _headline(rep: dict[str, Any]) -> str:
    totals = rep["totals"]
    usage = totals["usage"]
    return (f"**{fmt_tokens(totals['tokens'])} tokens** — input {fmt_tokens(usage['input'])} · "
            f"output {fmt_tokens(usage['output'])} · cache read {fmt_tokens(usage['cache_read'])} · "
            f"cache write {fmt_tokens(usage['cache_write_5m'] + usage['cache_write_1h'])} · "
            f"est. {fmt_cost(totals['cost_usd'])} · {_plural(totals['sessions'], 'session')} · "
            f"{_plural(totals['runs'], 'run')}")


def _span(start: str | None, end: str | None) -> str:
    if not start:
        return EMPTY
    first = parse_ts(start)
    if not end:
        return first.strftime("%m-%d %H:%M")
    last = parse_ts(end)
    tail = last.strftime("%H:%M") if last.date() == first.date() else last.strftime("%m-%d %H:%M")
    return f"{first.strftime('%m-%d %H:%M')} → {tail}"


def _models(run: dict[str, Any]) -> str:
    models = run.get("models") or {}
    ordered = sorted(models, key=lambda m: (-(models[m].get("calls") or 0), m))
    return ", ".join(ordered) if ordered else EMPTY


def _verdict(net: float | None) -> str:
    if net is None:
        return EMPTY
    return f"saved ≈ {fmt_cost(net)}" if net >= 0 else f"cost ≈ {fmt_cost(-net)} more"


def _compactions_line(compactions: list[dict[str, Any]]) -> str:
    triggers = Counter(c.get("trigger") or "unknown" for c in compactions)
    if len(triggers) == 1:
        kinds = next(iter(triggers))
    else:
        kinds = ", ".join(f"{count} {name}" for name, count in sorted(triggers.items()))
    largest = max(compactions, key=lambda c: c.get("pre_tokens") or 0)
    reload_tokens = sum(int(c.get("reload_tokens") or 0) for c in compactions)
    reload_cost = _sum_costs([c.get("reload_cost_usd") for c in compactions])
    return (f"Compactions: {len(compactions)} ({kinds}) · {fmt_tokens(largest.get('pre_tokens') or 0)} → "
            f"{fmt_tokens(largest.get('post_tokens') or 0)} · reload {fmt_tokens(reload_tokens)} "
            f"({fmt_cost(reload_cost)})")


def render_feature_md(sources: Sequence[dict[str, Any]]) -> str:
    """The merged ``token-usage.md`` (spec §4.1): byte-identical for the same set of sources."""
    rep = merge_feature(sources)
    lines = [GENERATED_COMMENT, f"# Token usage — {rep['feature'].get('id', '')}", "", _header(rep), "",
             _headline(rep), "",
             "| Phase | Sessions | Calls | Input | Output | Cache read | Cache write | Est. $ |",
             "|---|--:|--:|--:|--:|--:|--:|--:|"]
    for row in rep["phases"]:
        u = row["usage"]
        lines.append(f"| {_display(row['phase'])} | {row['sessions']} | {row['calls']} | {fmt_tokens(u['input'])} | "
                     f"{fmt_tokens(u['output'])} | {fmt_tokens(u['cache_read'])} | "
                     f"{fmt_tokens(u['cache_write_5m'] + u['cache_write_1h'])} | {_cell_cost(row['cost_usd'])} |")
    lines += ["", "## Runs", "",
              "| Phase | Run | Session | Author | Start → end (UTC) | Calls | Input | Output | Cache read | "
              "Cache write | Est. $ | Models | Subagents |",
              "|---|--:|---|---|---|--:|--:|--:|--:|--:|--:|---|--:|"]
    for run in rep["runs"]:
        u = run.get("usage") or _zero()
        mark = "†" if run.get("attributed_by") == "branch" else ""
        subagents = (run.get("subagents") or {}).get("count", 0)
        lines.append(f"| {_display(run['phase'])} | {run['run']} | {run['session_id'][:8]}{mark} | {run['author']} | "
                     f"{_span(run.get('start_ts'), run.get('end_ts'))} | {run.get('calls', 0)} | "
                     f"{fmt_tokens(u['input'])} | {fmt_tokens(u['output'])} | {fmt_tokens(u['cache_read'])} | "
                     f"{fmt_tokens(u['cache_write_5m'] + u['cache_write_1h'])} | {_cell_cost(run.get('cost_usd'))} | "
                     f"{_models(run)} | {subagents} |")
    lines.append("")

    if rep["splitting"] or rep["compactions"]:
        lines += ["## Session splitting", ""]
        if rep["splitting"]:
            lines += ["| Session | Author | Starts with | Re-primed | Carried context avoided | Verdict |",
                      "|---|---|---|--:|--:|---|"]
            for row in rep["splitting"]:
                primed = row["repriming"]
                split = row["splitting"]
                reprimed = f"{fmt_tokens(primed.get('tokens') or 0)} ({fmt_cost(primed.get('cost_usd'))})"
                if split:
                    carried = (f"{fmt_tokens(split.get('carried_tokens') or 0)} × {split.get('calls', 0)} calls "
                               f"({fmt_cost(split.get('avoided_cost_usd'))})")
                    verdict = _verdict(split.get("net_usd"))
                else:
                    carried, verdict = EMPTY, "no earlier session by this author"
                starts = _display(row["starts_with"]) if row["starts_with"] else EMPTY
                lines.append(f"| {row['session_id'][:8]} | {row['author']} | {starts} | {reprimed} | {carried} | "
                             f"{verdict} |")
            lines.append("")
            nets = [row["splitting"]["net_usd"] for row in rep["splitting"]
                    if row["splitting"] and row["splitting"].get("net_usd") is not None]
            if nets:
                total = sum(nets)
                if total >= 0:
                    lead = f"Splitting saved ≈ {fmt_cost(total)}"
                else:
                    lead = f"Splitting cost ≈ {fmt_cost(-total)} more"
                sentence = f"{lead} across {_plural(len(nets), 'comparable session')}. {ASSUMPTIONS}"
                lines += textwrap.wrap(sentence, width=WRAP_WIDTH, break_on_hyphens=False, break_long_words=False)
                lines.append("")
        if rep["compactions"]:
            lines += [_compactions_line(rep["compactions"]), ""]

    notes = []
    if any(run.get("attributed_by") == "branch" for run in rep["runs"]):
        notes.append(BRANCH_NOTE)
    if rep["unpriced_models"]:
        notes.append(f"Unpriced models (not included in the estimates): {', '.join(rep['unpriced_models'])}.")
    if rep["completeness"] == "partial":
        reasons = "; ".join(PARTIAL_TEXT.get(r, r) for r in rep["partial_reasons"]) or "incomplete data"
        notes.append(f"Partial data: {reasons} — a later capture completes it.")
    for note in notes:
        lines += [note, ""]
    lines += list(DISCLAIMER)
    return "\n".join(lines) + "\n"


# -- cross-feature rollup ------------------------------------------------------------------------

def merge_all(features: Sequence[dict[str, Any]], project: dict[str, Any],
              unattributed: dict[str, Any]) -> dict[str, Any]:
    """Cross-feature rollup of merged feature reports (schema usage-bridge/repo-report v1)."""
    ordered = sorted(features, key=lambda f: f["feature"].get("id", ""))
    rows = [{"id": f["feature"].get("id"), "directory": f["feature"].get("directory"),
             "sessions": f["totals"]["sessions"], "calls": f["totals"]["calls"], "tokens": f["totals"]["tokens"],
             "cost_usd": f["totals"]["cost_usd"], "phases": [p["phase"] for p in f["phases"]]} for f in ordered]
    stats: dict[str, dict[str, Any]] = {}
    for f in ordered:
        for p in f["phases"]:
            entry = stats.setdefault(p["phase"], {"kind": p["kind"], "tokens": [], "costs": []})
            entry["tokens"].append(p["tokens"])
            entry["costs"].append(p["cost_usd"])
    averages = []
    for phase, entry in sorted(stats.items(), key=lambda kv: _phase_key(kv[0], kv[1]["kind"])):
        known = [c for c in entry["costs"] if c is not None]
        averages.append({"phase": phase, "kind": entry["kind"], "features": len(entry["tokens"]),
                         "avg_tokens": round(sum(entry["tokens"]) / len(entry["tokens"])),
                         "avg_cost_usd": sum(known) / len(known) if known else None})
    return {"schema": SCHEMA_REPO, "schema_version": SCHEMA_VERSION, "features": rows, "phase_averages": averages,
            "project": dict(project), "unattributed": dict(unattributed)}


def render_all_md(report: dict[str, Any]) -> str:
    lines = ["# Token usage — all features", ""]
    if report["features"]:
        lines += ["| Feature | Sessions | Calls | Tokens | Est. $ | Phases |", "|---|--:|--:|--:|--:|---|"]
        for row in report["features"]:
            phases = ", ".join(_display(p) for p in row["phases"]) or EMPTY
            lines.append(f"| {row['id']} | {row['sessions']} | {row['calls']} | {fmt_tokens(row['tokens'])} | "
                         f"{_cell_cost(row['cost_usd'])} | {phases} |")
        lines += ["", "## Average per phase", "", "| Phase | Features | Avg tokens | Avg est. $ |", "|---|--:|--:|--:|"]
        for row in report["phase_averages"]:
            lines.append(f"| {_display(row['phase'])} | {row['features']} | {fmt_tokens(row['avg_tokens'])} | "
                         f"{_cell_cost(row['avg_cost_usd'])} |")
    else:
        lines.append("No feature has usage data yet.")
    lines += ["", "## Outside features", "", "| Bucket | Sessions | Calls | Tokens | Est. $ |", "|---|--:|--:|--:|--:|"]
    for label, data in (("project (constitution, this machine only)", report["project"]),
                        ("unattributed (this machine only)", report["unattributed"])):
        lines.append(f"| {label} | {data.get('sessions', 0)} | {data.get('calls', 0)} | "
                     f"{fmt_tokens(data.get('tokens', 0))} | {_cell_cost(data.get('cost_usd'))} |")
    lines += ["", *DISCLAIMER]
    return "\n".join(lines) + "\n"
