"""Coverage-aware summaries layered over the legacy report ordering."""
from collections import Counter

from .measurement import QUALITY

KEYS = ("input", "output", "cache_read", "cache_write_5m", "cache_write_1h")


def summarize_runs(runs):
    usage = {key: (None if any(row.get("usage", {}).get(key) is None for row in runs)
                   else sum(row.get("usage", {}).get(key, 0) for row in runs)) for key in KEYS}
    measured = {key: sum((row.get("measured_usage", row.get("usage", {})).get(key) or 0) for row in runs)
                for key in KEYS}
    costs = [row.get("cost_usd") for row in runs]
    known = [row.get("known_cost_usd", row.get("cost_usd")) for row in runs]
    return {"usage": usage, "measured_usage": measured,
            "tokens": None if any(v is None for v in usage.values()) else sum(usage.values()),
            "measured_tokens": sum(measured.values()),
            "calls": None if any(row.get("calls") is None for row in runs)
            else sum(row.get("calls", 0) for row in runs),
            "cost_usd": sum(costs) if costs and all(v is not None for v in costs) else None,
            "known_cost_usd": sum(v for v in known if v is not None) if any(v is not None for v in known) else None}


def enhance(report, sessions, runs):
    counts = Counter(session.get("measurement", "exact") for session in sessions)
    report["measurement_counts"] = {key: counts[key] for key in QUALITY}
    report["measurement"] = max(counts, key=lambda q: QUALITY[q], default="exact")
    report["runtimes"] = sorted({session.get("runtime", "claude") for session in sessions})
    report["totals"].update(summarize_runs(runs))
    for phase in report["phases"]:
        phase.update(summarize_runs([run for run in runs if run["phase"] == phase["phase"]]))
    report["runtime_breakdown"] = [{"runtime": runtime,
                                     **summarize_runs([r for r in runs if r.get("runtime", "claude") == runtime])}
                                    for runtime in report["runtimes"]]
    return report


def render_mixed(report, fmt_tokens, fmt_cost):
    total = report["totals"]
    def show(value):
        return "unavailable" if value is None else fmt_tokens(value)
    lines = ["<!-- Generated by Usage Bridge — do not edit. -->", "",
             f"# Token usage — {report['feature']['id']}", "",
             "Runtimes: " + ", ".join(report["runtimes"]),
             f"Measurement: {report['measurement']}; scan: {report['completeness']}", "",
             f"Measured token subtotal: {fmt_tokens(total['measured_tokens'])}. "
             "Unavailable coverage is excluded from this subtotal.",
             f"Complete cost: {fmt_cost(total['cost_usd'])}; known-cost subtotal: {fmt_cost(total['known_cost_usd'])}.",
             "", "| Phase | Runtime | Session | Author | Tokens | Measurement | Cost |",
             "|---|---|---|---|---:|---|---:|"]
    for run in report["runs"]:
        usage = run.get("usage", {})
        tokens = None if any(value is None for value in usage.values()) else sum(usage.values())
        cells = [run["phase"], run.get("runtime", "claude"), run["session_id"][:8], run["author"],
                 show(tokens), run.get("measurement", "exact"), fmt_cost(run.get("cost_usd"))]
        lines.append("| " + " | ".join(str(cell).replace("|", "\\|").replace("\n", " ") for cell in cells) + " |")
    lines += ["", "> Costs are API-price equivalent estimates; subscription plans are not billed per token."]
    return "\n".join(lines) + "\n"
